[package]
name = "amphora"
version = "0.1.1"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "amphora"
path = "src/main.rs"

[lib]
name = "amphora"
path = "src/amphora/lib.rs"

[dev-dependencies]
menmos-client = { version = "^0.1.1" }
portpicker = "0.1"
tempfile = "3.3"

[dependencies]
axum = "0.5.0"
axum-server = { version = "0.3.3", features = ["tls-rustls"] }
tower-http = { version = "0.2.5", features = ["trace"] }
hyper = "0.14.18"

anyhow = "1"
async-trait = "0.1.53"
base64 = "0.13"
bincode = "1.3.1"
bytes = "1.0"
chrono = "0.4"
clap = { version = "3.1.8", features = ["derive"] }
config = { git = "https://github.com/dalloriam/config-rs", branch = "parse-env-numbers" }
dirs = "4"
futures = "0.3"
headers = "0.3"
http = "=0.2.6"
local_ipaddress = "0.1.3"
machine-uid = "0.2.0"
menmos-apikit = { version = "^0.1.1" }
menmos-auth = { version = "^0.1.1" }
menmos-interface = { version = "^0.1.1" }
menmos-protocol = { version = "^0.1.1" }
menmos-repository = { version = "^0.1.1" }
menmos-std = { version = "^0.1.1" }
menmos-xecute = { version = "^0.1.1" }
parking_lot = "0.12.0"
public-ip = { git = "https://github.com/avitex/rust-public-ip", rev = "09c3c33" } # TODO: Update to v0.2
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sled = { git = "https://github.com/spacejam/sled", branch = "main" }
tokio = { version = "1.16", features = ["full"] }
tracing = { version = "0.1", features = ["max_level_trace", "release_max_level_debug"] }
