[package]
name = "amphora"
version = "0.0.10"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "amphora"
path = "src/main.rs"

[lib]
name = "amphora"
path = "src/amphora/lib.rs"

[dev-dependencies]
menmos-client = {version = "^0.0.10"}
portpicker = "0.1"
tempfile = "3.2"

[dependencies]
anyhow = "1"
async-trait = "0.1.42"
base64 = "0.13"
bincode = "1.3.1"
bytes = "1.0"
chrono = "0.4"
clap = {version = "3.0.0-rc.9", features = ["derive"]}
config = {git = "https://github.com/dalloriam/config-rs", branch = "parse-env-numbers"}
dirs = "3"
futures = "0.3"
headers = "=0.3.3"
http = "=0.2.5"
local_ipaddress = "0.1.3"
machine-uid = "0.2.0"
menmos-apikit = {version = "^0.0.10"}
menmos-interface = {version = "^0.0.10"}
menmos-protocol = {version = "^0.0.10"}
menmos-repository = {version = "^0.0.10"}
menmos-std = {version = "^0.0.10"}
menmos-xecute = {version = "^0.0.10"}
mime = "0.3"
mpart-async = "0.5"
public-ip = {git = "https://github.com/avitex/rust-public-ip", rev = "09c3c33"} # TODO: Update to v0.2
reqwest = {version = "0.11", features = ["json"]}
rusoto_core = "0.46"
rusoto_s3 = "0.46"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
sled = "0.34"
tokio = {version = "1.2", features = ["full"]}
tracing = {version = "0.1", features = ["max_level_trace", "release_max_level_debug"]}
warp = {version = "0.3", features = ["tls"]}
