[package]
name = "amphora"
version = "0.0.2-alpha.2"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "amphora"
path = "src/main.rs"

[lib]
name = "amphora"
path = "src/amphora/lib.rs"

[dev-dependencies]
menmos-client = {path = "../../crates/menmos-client"}
portpicker = "0.1"
tempfile = "3.2"

[dependencies]
anyhow = "1"
async-trait = "0.1.42"
apikit = {path = "../../crates/apikit"}
base64 = "0.13"
bincode = "1.3.1"
bytes = "1.0"
clap = "3.0.0-beta.2"
config = {git = "https://github.com/dalloriam/config-rs", branch = "parse-env-numbers"}
dirs = "3"
futures = "0.3"
headers = "=0.3.3"
http = "=0.2.3"
interface = {path = "../../crates/interface"}
local_ipaddress = "0.1.3"
log4rs = "1"
log = "0.4"
machine-uid = "0.2.0"
mime = "0.3"
mpart-async = "0.5"
protocol = {path = "../../crates/protocol"}
public-ip = {git = "https://github.com/avitex/rust-public-ip", rev = "09c3c33"}
repository = {path = "../../crates/repository"}
reqwest = {version = "0.11", features = ["json"]}
rusoto_core = "0.46"
rusoto_s3 = "0.46"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
sled = "0.34"
tokio = {version = "1.2", features = ["full"]}
warp = {version = "0.3", features = ["tls"]}
