[package]
name = "menmosd"
version = "0.1.0"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "menmosd"
path = "src/main.rs"

[lib]
name = "menmosd"
path = "src/menmosd/lib.rs"

[dev-dependencies]
amphora = {path = "../amphora"}
menmos-client = {path = "../../crates/menmos-client"}
portpicker = "0.1"
tempfile = "3.2"

[dependencies]
acme-lib = "0.8"
anyhow = "1"
apikit = {path = "../../crates/apikit"}
async-trait = "0.1.42"
base64 = "0.13"
bincode = "1.3.1"
bitvec = {version = "0.20", features = ["serde"]}
byteorder = "1.4.2"
bytes = "1.0"
chrono = {version = "0.4", features = ["serde"]}
clap = "3.0.0-beta.2"
config = {git = "https://github.com/dalloriam/config-rs", branch = "parse-env-numbers"}
dirs = "3"
dns-server = {path = "../../crates/dns-server"}
env_logger = "0.8"
external-ip = "=4.1.0"
futures = "0.3"
headers = "=0.3.3"
indexer = {path = "../../crates/indexer"}
interface = {path = "../../crates/interface"}
ipnetwork = "0.17"
log = "0.4"
log4rs = "1"
mime = "0.3"
rapidquery = {path = "../../crates/rapidquery", features=["bitvec_span"]}
reqwest = {version = "0.11", features = ["json", "stream"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
sled = {git = "https://github.com/spacejam/sled", branch = "main"}
tokio = {version = "1.2", features = ["full"]}
urlsign = {path = "../../crates/urlsign"}
uuid = { version = "0.8", features = ["serde", "v4"] }
warp = {version = "0.3", features = ["tls"]}
x509-parser = "0.9"
