[package]
name = "menmosd"
version = "0.2.6"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "menmosd"
path = "src/main.rs"

[lib]
name = "menmosd"
path = "src/menmosd/lib.rs"

[features]
default = []
webui = ["include_dir"]
menmos_debug = []

[dev-dependencies]
amphora = { path = "../amphora" }
menmos-client = { version = "^0.2.6" }
menmos-testing = { path = "../../crates/menmos-testing" }
portpicker = "0.1"
reqwest = { version = "0.11", features = ["json", "stream"] }
tempfile = "3.3"

[build-dependencies]
anyhow = "1"

[dependencies]
axum = "0.5.11"
axum-server = { version = "0.4.0", features = ["tls-rustls"] }
axum-client-ip = { version = "0.2.0" }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["trace", "cors"] }
tower-request-id = "0.2.0"
hyper = "0.14.19"

acme-lib = "0.8"
anyhow = "1"
async-trait = "0.1.56"
base64 = "0.13"
bincode = "1.3.1"
bitvec = { version = "1.0", features = ["serde"] }
byteorder = "1.4.2"
bytes = "1.0"
clap = { version = "3.2.8", features = ["derive"] }
config = { version = "0.13.1", features = ["toml"] }
dirs = "4"
external-ip = "=4.1.0"
futures = "0.3"
headers = "0.3"
ipnetwork = "0.20"
menmos-antidns = { version = "^0.2.6" }
menmos-apikit = { version = "^0.2.6" }
menmos-auth = { version = "^0.2.6" }
menmos-interface = { version = "^0.2.6" }
menmos-protocol = { version = "^0.2.6" }
menmos-std = { version = "^0.2.6" }
menmos-xecute = { version = "^0.2.6" }
opentelemetry = { version = "0.17.0", features = ["rt-tokio"] }
opentelemetry-http = "0.6.0"
parking_lot = "0.12.1"
rapidquery = { version = "^0.2.6", features = ["bitvec_size"] }
ring = "0.16"
rust-argon2 = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sled = { git = "https://github.com/spacejam/sled", branch = "main" }
time = { version = "0.3.11", features = ["serde"] }
tracing = { version = "0.1", features = ["max_level_trace", "release_max_level_debug"] }
tracing-opentelemetry = "0.17.4"
tokio = { version = "1.18", features = ["full"] }
uuid = { version = "1.1", features = ["v4", "fast-rng", "serde"] }
x509-parser = "0.14"

include_dir = { version = "0.7.2", optional = true }
