[package]
name = "menmosd"
version = "0.0.10"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "menmosd"
path = "src/main.rs"

[lib]
name = "menmosd"
path = "src/menmosd/lib.rs"

[features]
default = []
webui = ["include_dir"]
menmos_debug = []

[dev-dependencies]
amphora = {path = "../amphora"}
menmos-client = {path = "../../crates/menmos-client"}
menmos-testing = {path = "../../crates/menmos-testing"}
portpicker = "0.1"
reqwest = {version = "0.11", features = ["json", "stream"]}
tempfile = "3.2"

[build-dependencies]
anyhow = "1"

[dependencies]
acme-lib = "0.8"
anyhow = "1"
async-trait = "0.1.42"
base64 = "0.13"
bincode = "1.3.1"
bitvec = {version = "0.22", features = ["serde"]}
byteorder = "1.4.2"
bytes = "1.0"
chrono = {version = "0.4", features = ["serde"]}
clap = {version = "3.0.4", features = ["derive"]}
config = {git = "https://github.com/dalloriam/config-rs", branch = "parse-env-numbers"}
dirs = "4"
external-ip = "=4.1.0"
futures = "0.3"
headers = "=0.3.5"
ipnetwork = "0.18"
menmos-antidns = {version = "^0.0.10"}
menmos-apikit = {version = "^0.0.10"}
menmos-interface = {version = "^0.0.10"}
menmos-protocol = {version = "^0.0.10"}
menmos-std = {version = "^0.0.10"}
menmos-xecute = {version = "^0.0.10"}
mime = "0.3"
rapidquery = {version = "^0.0.10", features=["bitvec_span"]}
ring = "0.16"
rust-argon2 = "0.8"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
sled = {git = "https://github.com/spacejam/sled", branch = "main"}
tracing = {version = "0.1", features = ["max_level_trace", "release_max_level_debug"]}
tokio = {version = "1.2", features = ["full"]}
uuid = { version = "0.8", features = ["serde", "v4"] }
warp = {version = "0.3", features = ["tls"]}
x509-parser = "0.12"

include_dir = {version = "0.7.2", optional = true}
