[workspace]
members = [
    "bin/amphora",
    "bin/menmos-cli",
    "bin/menmosd",
    "bin/menmos-fuse",
    "crates/apikit",
    "crates/betterstreams",
    "crates/dns-server",
    "crates/indexer",
    "crates/interface",
    "crates/lfan",
    "crates/menmos-client",
    "crates/rapidquery",
    "crates/repository",
    "crates/testing",
]
