[package]
name = "lfan"
version = "0.0.4-alpha.0"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
async = ["tokio"]

[dependencies]
linked-hash-map = "0.5"
tokio = {version = "1.2", features = ["sync"], optional = true}
