[package]
name = "menmos-cli"
version = "0.0.5-alpha.4"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "mmos"
path = "src/main.rs"

[lib]
name = "service"
path = "src/service/lib.rs"

[dependencies]
anyhow = "1"
async-stream = "0.3"
clap = "3.0.0-beta.2"
dirs = "3"
futures = "0.3"
menmos-client = "0.0.5"
menmos-interface = "0.0.5"
serde = {version = "1", features = ["derive"]}
tokio = {version = "1.2", features = ["full"]}
walkdir = "2.3"

[target.'cfg(target_family = "unix")'.dependencies]
nix = "0.17.0"

[dependencies.rood]
version = "0.4"
default-features = false
features = ["cli"]
