[package]
name = "menmos-cli"
version = "0.0.10"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "mmos"
path = "src/main.rs"

[lib]
name = "service"
path = "src/service/lib.rs"

[dependencies]
anyhow = "1"
async-stream = "0.3"
clap = {version = "3.0.0-rc.9", features=["derive"]}
dirs = "4"
futures = "0.3"
menmos-client = {version = "^0.0.10"}
menmos-interface = { version = "^0.0.10"}
serde = {version = "1", features = ["derive"]}
tokio = {version = "1.2", features = ["full"]}
walkdir = "2.3"

[target.'cfg(target_family = "unix")'.dependencies]
nix = "0.23.1"

[dependencies.rood]
version = "0.5"
default-features = false
features = ["cli"]
