[package]
name = "menmos-cli"
version = "0.1.0"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "mmos"
path = "src/main.rs"

[lib]
name = "service"
path = "src/service/lib.rs"

[dependencies]
anyhow = "1"
async-stream = "0.3"
clap = "3.0.0-beta.2"
menmos-client = {path = "../../crates/menmos-client"}
dirs = "3"
futures = "0.3"
interface = {path = "../../crates/interface"}
serde = {version = "1", features = ["derive"]}
tokio = {version = "0.2", features = ["full"]}
walkdir = "2.3"

[dependencies.rood]
version = "0.3.2"
default-features = false
features = ["cli"]
