[package]
name = "menmos-cli"
version = "0.2.6"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "mmos"
path = "src/main.rs"

[lib]
name = "service"
path = "src/service/lib.rs"

[dependencies]
anyhow = "1"
clap = {version = "3.2.8", features=["derive"]}
dirs = "4"
futures = "0.3"
menmos = {version = "0.2.6" }
serde = {version = "1", features = ["derive"]}
tokio = {version = "1.18", features = ["full"]}
tracing = { version = "0.1", features = ["max_level_trace", "release_max_level_debug"] }
walkdir = "2.3"

[target.'cfg(target_family = "unix")'.dependencies]
nix = "0.24.1"

[dependencies.rood]
version = "0.5"
default-features = false
features = ["cli"]
