[package]
name = "menmos-protocol"
version = "0.0.5-alpha.4"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2018"

[lib]
name = "protocol"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
menmos-interface = {path = "../menmos-interface"}
rapidquery = {path = "../rapidquery"}
serde = {version = "1", features = ["derive"]}
