[package]
name = "menmos-std"
version = "0.1.1"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Menmos library containing protocol payloads"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.16", features = ["full"]}
