[package]
name = "menmos-client"
version = "0.0.9"
license = "Apache-2.0"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2018"
description = "Menmos entrypoint library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
bytes = "1"
dirs = "3"
futures = "0.3"
hyper = "0.14"
menmos-apikit = {version = "^0.0.9"}
menmos-interface = {version = "^0.0.9"}
menmos-protocol = {version = "^0.0.9"}
mpart-async = "0.5"
reqwest = {version = "0.11", features = ["json"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
snafu = "0.6"
tokio = {version = "1.2", features = ["full"]}
toml = "0.5"
tracing = {version = "0.1", features = ["max_level_trace", "release_max_level_debug"]}
