[package]
name = "menmos-client"
version = "0.0.2-alpha.0"
authors = ["William Dussault <dalloriam@gmail.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apikit = {path = "../apikit"}
base64 = "0.13"
bytes = "1"
dirs = "3"
futures = "0.3"
hyper = "0.14"
mpart-async = "0.5"
interface = {path = "../interface"}
log = "0.4"
reqwest = {version = "0.11", features = ["json"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
snafu = "0.6"
tokio = {version = "1.2", features = ["full"]}
toml = "0.5"
