name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - '*'

jobs:
  unit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install
        if: matrix.os == 'windows-latest'
        run: |
          git clone https://github.com/microsoft/vcpkg
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg integrate install
          .\vcpkg\vcpkg install openssl:x64-windows-static-md
        shell: pwsh

      - uses: Swatinem/rust-cache@v1

      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --lib

  integration:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install OpenSSL
        if: matrix.os == 'windows-latest'
        run: |
          git clone https://github.com/microsoft/vcpkg
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg integrate install
          .\vcpkg\vcpkg install openssl:x64-windows-static-md
        shell: pwsh

      - uses: Swatinem/rust-cache@v1

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          arg: --test '*'
