name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    env:
      VCPKGRS_DYNAMIC: 1
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install
        if: matrix.os == 'windows-latest'
        run: |
          git clone https://github.com/microsoft/vcpkg
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg integrate install
          .\vcpkg\vcpkg install openssl:x64-windows-static-md
        shell: pwsh

      - run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
        if: matrix.os == 'windows-latest'

      - run: vcpkg install openssl:x64-windows
        if: matrix.os == 'windows-latest'

      - uses: actions/cache@v1
        with:
          path: ~/.cargo/registry/index
          key: index-${{ runner.os }}-${{ github.run_number }}
          restore-keys: |
            index-${{ runner.os }}-

      - uses: Swatinem/rust-cache@v1

      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
